# Generated by Django 4.1.7 on 2023-02-17 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subtitleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
